FORMAT: 1A
HOST: http://bookman-core.herokuapp.com/

# Bookman

A web service that enables easy management of Bookman resources (basically books).

## User Management [/api/v1/UserService]
### Subscribe [POST]
    
    Subscribe the the Bookman service and obtaine subscription key (token).
    
+ Request (application/xml)

        <?xml version="1.0" encoding="UTF-8"?>
        <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://wsdl.example.org/">
            <SOAP-ENV:Body>
                <Subscribe>
                    <email>new-account@email.com</email>
                </Subscribe>
            </SOAP-ENV:Body>
        </SOAP-ENV:Envelope>

+ Response 200 (application/xml)

        <?xml version="1.0" encoding="UTF-8"?>
        <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://localhost:8000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://xml.apache.org/xml-soap" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
            <SOAP-ENV:Body>
                <ns1:SubscribeResponse>
                    <return xsi:type="ns2:Map">
                        <item>
                            <key xsi:type="xsd:string">email</key>
                            <value xsi:type="xsd:string">new-account@email.com</value>
                        </item>
                        <item>
                            <key xsi:type="xsd:string">token</key>
                            <value xsi:type="xsd:string">{ NEW_TOKEN }</value>
                        </item>
                        <item>
                            <key xsi:type="xsd:string">message</key>
                            <value xsi:type="xsd:string">Subscription successful. Ensure to copy and store the generated token.</value>
                        </item>
                    </return>
                </ns1:SubscribeResponse>
            </SOAP-ENV:Body>
        </SOAP-ENV:Envelope>
        
### Update Profile [POST]

    Update your profile and get new key (token).
    
+ Request (application/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://wsdl.example.org/">
        <SOAP-ENV:Body>
            <UpdateProfile>
                <oldEmail>new-account@email.com</oldEmail>
                <newEmail>updated-account@email.com</newEmail>
                <token>{ SUBSCRIPTION_TOKEN }</token>
            </UpdateProfile>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>

+ Response 200 (application/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://localhost:8000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://xml.apache.org/xml-soap" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <SOAP-ENV:Body>
            <ns1:UpdateProfileResponse>
                <return xsi:type="ns2:Map">
                    <item>
                        <key xsi:type="xsd:string">email</key>
                        <value xsi:type="xsd:string">updated-account@email.com</value>
                    </item>
                    <item>
                        <key xsi:type="xsd:string">token</key>
                        <value xsi:type="xsd:string">{ NEW_TOKEN }</value>
                    </item>
                    <item>
                        <key xsi:type="xsd:string">message</key>
                        <value xsi:type="xsd:string">Profile updated successful. Ensure to copy and store the generated token.</value>
                    </item>
                </return>
            </ns1:UpdateProfileResponse>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>

## Book Management [/api/v1/BookService]

### Add New Book [POST]

    Add a new book to your list.
    
+ Request (applicaiton/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://wsdl.example.org/">
        <SOAP-ENV:Body>
            <AddBook>
                <title>Things Fall Apart</title>
                <token>{ SUBSCRIPTION_TOKEN }</token>
            </AddBook>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
    
+ Response 201 (application/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://localhost:8000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://xml.apache.org/xml-soap" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <SOAP-ENV:Body>
            <ns1:AddBookResponse>
                <return xsi:type="ns2:Map">
                    <item>
                        <key xsi:type="xsd:string">book</key>
                        <value xsi:type="ns2:Map">
                            <item>
                                <key xsi:type="xsd:string">id</key>
                                <value xsi:type="xsd:int">1</value>
                            </item>
                            <item>
                                <key xsi:type="xsd:string">title</key>
                                <value xsi:type="xsd:string">Things Fall Apart</value>
                            </item>
                        </value>
                    </item>
                    <item>
                        <key xsi:type="xsd:string">message</key>
                        <value xsi:type="xsd:string">A new book was created successful.</value>
                    </item>
                </return>
            </ns1:AddBookResponse>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>

### Get A Book [POST]

    Get a book from your list.
    
+ Request (applicaiton/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://wsdl.example.org/">
        <SOAP-ENV:Body>
            <GetBook>
                <id>1</id>
                <token>{ SUBSCRIPTION_TOKEN }</token>
            </GetBook>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
    
+ Response 200 (application/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://localhost:8000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://xml.apache.org/xml-soap" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <SOAP-ENV:Body>
            <ns1:GetBookResponse>
                <return xsi:type="ns2:Map">
                    <item>
                        <key xsi:type="xsd:string">book</key>
                        <value xsi:type="ns2:Map">
                            <item>
                                <key xsi:type="xsd:string">id</key>
                                <value xsi:type="xsd:int">1</value>
                            </item>
                            <item>
                                <key xsi:type="xsd:string">title</key>
                                <value xsi:type="xsd:string">Things Fall Apart</value>
                            </item>
                        </value>
                    </item>
                    <item>
                        <key xsi:type="xsd:string">message</key>
                        <value xsi:type="xsd:string">Book found</value>
                    </item>
                </return>
            </ns1:GetBookResponse>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
    
### Get Books [POST]

    Get the books in your list.
    
+ Request (applicaiton/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://wsdl.example.org/">
        <SOAP-ENV:Body>
            <GetBooks>
                <token>{ SUBSCRIPTION_TOKEN }</token>
            </GetBooks>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
    
+ Response 200 (application/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://localhost:8000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://xml.apache.org/xml-soap" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <SOAP-ENV:Body>
            <ns1:GetBooksResponse>
                <return xsi:type="ns2:Map">
                    <item>
                        <key xsi:type="xsd:string">books</key>
                        <value SOAP-ENC:arrayType="ns2:Map[1]" xsi:type="SOAP-ENC:Array">
                            <item xsi:type="ns2:Map">
                                <item>
                                    <key xsi:type="xsd:string">id</key>
                                    <value xsi:type="xsd:int">1</value>
                                </item>
                                <item>
                                    <key xsi:type="xsd:string">title</key>
                                    <value xsi:type="xsd:string">Things Fall Apart</value>
                                </item>
                            </item>
                        </value>
                    </item>
                    <item>
                        <key xsi:type="xsd:string">message</key>
                        <value xsi:type="xsd:string">Books found</value>
                    </item>
                </return>
            </ns1:GetBooksResponse>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
    
### Update a Book [POST]

    Update a book in your list.
    
+ Request (applicaiton/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://wsdl.example.org/">
        <SOAP-ENV:Body>
            <UpdateBook>
                <id>1</id>
                <newTitle>Things have fallen apart</newTitle>
                <token>{ SUBSCRIPTION_TOKEN }</token>
            </UpdateBook>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
    
+ Response 200 (application/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://localhost:8000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://xml.apache.org/xml-soap" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <SOAP-ENV:Body>
            <ns1:UpdateBookResponse>
                <return xsi:type="ns2:Map">
                    <item>
                        <key xsi:type="xsd:string">book</key>
                        <value xsi:type="ns2:Map">
                            <item>
                                <key xsi:type="xsd:string">id</key>
                                <value xsi:type="xsd:int">1</value>
                            </item>
                            <item>
                                <key xsi:type="xsd:string">title</key>
                                <value xsi:type="xsd:string">Things have fallen apart</value>
                            </item>
                        </value>
                    </item>
                    <item>
                        <key xsi:type="xsd:string">message</key>
                        <value xsi:type="xsd:string">Book updated successfully</value>
                    </item>
                </return>
            </ns1:UpdateBookResponse>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
    
### Delete a Book [POST]

    Delete a book from your list.
    
+ Request (applicaiton/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://wsdl.example.org/">
        <SOAP-ENV:Body>
            <DeleteBook>
                <id>3</id>
                <token>{ SUBSCRIPTION_TOKEN }</token>
            </DeleteBook>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
    
+ Response 204 (application/xml)

    <?xml version="1.0" encoding="UTF-8"?>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://localhost:8000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://xml.apache.org/xml-soap" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <SOAP-ENV:Body>
            <ns1:DeleteBookResponse>
                <return xsi:type="ns2:Map">
                    <item>
                        <key xsi:type="xsd:string">message</key>
                        <value xsi:type="xsd:string">Book deleted successfully</value>
                    </item>
                </return>
            </ns1:DeleteBookResponse>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>